import type { Pool } from 'pg';
import { analyzeText } from '../moderation.ts';
import { forbidden, notFound } from '../errors.ts';
import { parseSearchIntent } from './intent.ts';
import type { AiProvider } from './providers.ts';

export type AiTask =
  | 'caption'
  | 'summarize_conversation'
  | 'summarize_community'
  | 'search_intent'
  | 'plan_from_message'
  | 'translate';

export interface AiRequest {
  userId: string;
  task: AiTask;
  input: string;
  conversationId?: string;
  communityId?: string;
  targetLanguage?: string;
}

export interface AiResponse {
  task: AiTask;
  output: unknown;
  provider: string;
  model: string;
  /** Data the model was allowed to read for this request. */
  contextScopes: string[];
  notice?: string;
}

/**
 * AI Gateway → Permission Engine → Context Engine → Model Router → Safety Layer → Response.
 *
 * Authorization happens BEFORE any context is loaded, and context only ever
 * contains data the requesting user can already see. Every call is logged to
 * ai_tool_calls (task, scopes, provider, status) without storing content.
 */
export class AiGateway {
  constructor(
    private db: Pool,
    private provider: AiProvider,
  ) {}

  get providerName() {
    return this.provider.name;
  }

  async run(req: AiRequest): Promise<AiResponse> {
    const started = Date.now();
    let scopes: string[] = [];
    try {
      // 1. Permission engine + 2. context engine
      const ctx = await this.loadContext(req);
      scopes = ctx.scopes;

      // Input safety: refuse to process content that is itself high-risk.
      if (analyzeText(req.input).risk === 'escalate') throw forbidden('This request can’t be processed.');

      // 3. Model router + 4. task execution
      const output = await this.execute(req, ctx.text);

      // 5. Output safety layer
      const flat = typeof output === 'string' ? output : JSON.stringify(output);
      if (analyzeText(flat).risk === 'escalate' || analyzeText(flat).risk === 'restrict') {
        await this.log(req, scopes, 'blocked', started);
        return { task: req.task, output: null, provider: this.provider.name, model: this.provider.model, contextScopes: scopes, notice: 'The result was withheld by safety filters.' };
      }
      await this.log(req, scopes, 'ok', started);
      return {
        task: req.task,
        output,
        provider: this.provider.name,
        model: this.provider.model,
        contextScopes: scopes,
        notice: this.provider.name === 'dev' ? 'Generated by the local development provider (rule-based, no model).' : undefined,
      };
    } catch (err) {
      const status = (err as { status?: number }).status === 403 ? 'denied' : 'error';
      await this.log(req, scopes, status, started);
      throw err;
    }
  }

  private async loadContext(req: AiRequest): Promise<{ text: string; scopes: string[] }> {
    if (req.task === 'summarize_conversation') {
      if (!req.conversationId) throw notFound('Conversation');
      const member = await this.db.query(
        `SELECT 1 FROM conversation_members WHERE conversation_id = $1 AND user_id = $2 AND left_at IS NULL`,
        [req.conversationId, req.userId],
      );
      if (!member.rowCount) throw notFound('Conversation');
      const { rows } = await this.db.query<{ name: string; body: string }>(
        `SELECT p.display_name AS name, m.body FROM messages m JOIN profiles p ON p.user_id = m.sender_id
         WHERE m.conversation_id = $1 AND m.deleted_at IS NULL ORDER BY m.created_at DESC LIMIT 200`,
        [req.conversationId],
      );
      return { text: rows.reverse().map((r) => `${r.name}: ${r.body}`).join('\n'), scopes: [`conversation:${req.conversationId}`] };
    }
    if (req.task === 'summarize_community') {
      if (!req.communityId) throw notFound('Community');
      const c = await this.db.query<{ visibility: string; role: string | null }>(
        `SELECT c.visibility, cm.role FROM communities c
         LEFT JOIN community_members cm ON cm.community_id = c.id AND cm.user_id = $2 AND cm.status = 'active'
         WHERE c.id = $1 AND c.deleted_at IS NULL`,
        [req.communityId, req.userId],
      );
      const row = c.rows[0];
      if (!row || (row.visibility === 'private' && !row.role)) throw notFound('Community');
      const { rows } = await this.db.query<{ name: string; body: string }>(
        `SELECT pr.display_name AS name, p.body FROM posts p JOIN profiles pr ON pr.user_id = p.author_id
         WHERE p.community_id = $1 AND p.deleted_at IS NULL AND p.moderation_status = 'normal'
         ORDER BY p.created_at DESC LIMIT 100`,
        [req.communityId],
      );
      return { text: rows.map((r) => `${r.name}: ${r.body}`).join('\n'), scopes: [`community:${req.communityId}`] };
    }
    // caption, search_intent, plan_from_message and translate only use the text the user supplied.
    return { text: req.input, scopes: ['input'] };
  }

  private async execute(req: AiRequest, context: string): Promise<unknown> {
    if (this.provider.name === 'dev') return devTask(req, context);
    const prompts: Record<AiTask, { system: string; prompt: string }> = {
      caption: {
        system: 'You write short social media captions. Reply with the caption only, under 200 characters, no hashtags unless asked.',
        prompt: `Write a caption for a post about:\n${context}`,
      },
      summarize_conversation: {
        system: 'Summarize a group chat for someone catching up. Use 3-6 short bullet points. Only use facts stated in the messages; do not invent decisions.',
        prompt: context || '(no messages)',
      },
      summarize_community: {
        system: 'Summarize recent community discussion in 3-6 short bullet points. Only report what members actually said; never state a community decision that was not explicitly made.',
        prompt: context || '(no posts)',
      },
      search_intent: {
        system: 'Rewrite the search request as 2-6 plain keywords. Reply with keywords only.',
        prompt: context,
      },
      plan_from_message: {
        system: 'Extract a plan from the message as JSON with keys destination, dates, participants, budget, activities (array), tasks (array). Use null when unknown. Reply with JSON only.',
        prompt: context,
      },
      translate: {
        system: `Translate the text into ${req.targetLanguage ?? 'English'}. Reply with the translation only.`,
        prompt: context,
      },
    };
    const p = prompts[req.task];
    const res = await this.provider.complete({ system: p.system, prompt: p.prompt, maxTokens: req.task === 'caption' ? 300 : 2000 });
    if (res.refused) return null;
    if (req.task === 'search_intent') return { ...parseSearchIntent(req.input), terms: res.text };
    if (req.task === 'plan_from_message') {
      try {
        return JSON.parse(res.text.replace(/^```(json)?|```$/g, '').trim());
      } catch {
        return devTask(req, context);
      }
    }
    if (req.task === 'translate') return { original: req.input, translated: res.text, targetLanguage: req.targetLanguage ?? 'en' };
    return res.text;
  }

  private async log(req: AiRequest, scopes: string[], status: string, started: number) {
    await this.db
      .query(
        `INSERT INTO ai_tool_calls (user_id, task, provider, model, context_scopes, status, latency_ms) VALUES ($1,$2,$3,$4,$5,$6,$7)`,
        [req.userId, req.task, this.provider.name, this.provider.model, scopes, status, Date.now() - started],
      )
      .catch(() => {});
  }
}

/** Rule-based implementations used by the dev provider. Deterministic and offline. */
function devTask(req: AiRequest, context: string): unknown {
  switch (req.task) {
    case 'caption': {
      const first = context.split(/(?<=[.!?])\s/)[0]?.trim() ?? '';
      return first.length > 140 ? `${first.slice(0, 137)}…` : first;
    }
    case 'summarize_conversation':
    case 'summarize_community': {
      const lines = context.split('\n').filter(Boolean);
      if (!lines.length) return 'Nothing to summarize yet.';
      const people = [...new Set(lines.map((l) => l.split(':')[0]))];
      const longest = [...lines].sort((a, b) => b.length - a.length).slice(0, 3);
      return [`${lines.length} messages from ${people.join(', ')}.`, ...longest.map((l) => `• ${l}`)].join('\n');
    }
    case 'search_intent':
      return parseSearchIntent(req.input);
    case 'plan_from_message': {
      const dest = context.match(/\b(?:to|in|visit)\s+([A-Z][\p{L}-]+(?:\s[A-Z][\p{L}-]+)?)/u)?.[1] ?? null;
      const dates = context.match(/\b(tonight|tomorrow|this weekend|next (?:week|month|year)|on \w+day|in \w+)\b/i)?.[1] ?? null;
      return { destination: dest, dates, participants: [], budget: null, transport: null, accommodation: null, activities: [], tasks: dest ? [`Book travel to ${dest}`] : [] };
    }
    case 'translate':
      return { original: req.input, translated: null, targetLanguage: req.targetLanguage ?? 'en', notice: 'Translation needs a configured AI provider.' };
  }
}
