import type { PostCardLabels } from './domain/post-card';
import type { CommentLabels } from './domain/comment-thread';
import type { ComposerLabels } from './domain/composer';
import type { PostData, CommentData } from './domain/types';
import type { ProfileHeaderLabels } from './domain/profile-header';

export const pollLabels = {
  vote: 'Vote',
  voting: 'Voting',
  chooseOne: 'Choose one',
  chooseMany: 'Choose any',
  votesTotal: (n: number) => `${n} votes`,
  closesAt: (w: string) => `Closes ${w}`,
  closed: 'Closed',
  yourVote: 'Your vote',
  pickAtLeastOne: 'Pick at least one option',
};

export const postLabels: PostCardLabels = {
  like: 'Like',
  save: 'Save',
  comment: 'Comments',
  share: 'Share',
  shareOnlyPublic: 'Only public posts can be shared',
  moreMenu: 'Post options',
  reactionMenu: 'Choose a reaction',
  reactions: {
    like: 'Like',
    love: 'Love',
    laugh: 'Laugh',
    wow: 'Wow',
    sad: 'Sad',
    insightful: 'Insightful',
  },
  visibility: {
    public: 'Public',
    followers: 'Followers',
    friends: 'Friends',
    circle: 'Circle',
    selected: 'Selected people',
    private: 'Only me',
    community: 'Community',
  },
  edited: 'edited',
  likesCount: (n) => `${n} likes`,
  commentsCount: (n) => `${n} comments`,
  authorLink: (n) => `Profile of ${n}`,
  topics: 'Topics',
  moreLikeThis: 'More like this',
  lessLikeThis: 'Less like this',
  notInterested: 'Not interested',
  muteCreator: (u) => `Mute @${u}`,
  muteTopic: (t) => `Mute topic ${t}`,
  linkPreview: 'Link',
  loadMedia: 'Load',
  mediaHiddenLowBandwidth: 'Media hidden to save data',
  poll: pollLabels,
  reasons: {
    trigger: 'Why am I seeing this?',
    title: 'Why you are seeing this post',
    intro: 'Reasons',
    loading: 'Loading reasons',
    error: 'Could not load',
    retry: 'Try again',
    controlsTitle: 'Tune your feed',
    moreLikeThis: 'More like this',
    lessLikeThis: 'Less like this',
    notInterested: 'Not interested',
    muteCreator: 'Mute creator',
    done: 'Done',
    feedbackSent: 'Thanks, noted',
  },
};

export const commentLabels: CommentLabels = {
  heading: 'Comments',
  empty: 'No comments yet',
  placeholder: 'Add a comment',
  submit: 'Comment',
  submitting: 'Sending',
  reply: 'Reply',
  replyTo: (n) => `Reply to ${n}`,
  cancel: 'Cancel',
  like: 'Like',
  likesCount: (n) => `${n} likes`,
  delete: 'Delete',
  deleteAria: (n) => `Delete comment by ${n}`,
  showReplies: (n) => `Show ${n} replies`,
  hideReplies: 'Hide replies',
  moreReplies: 'More replies',
  loadMore: 'Load more',
  loading: 'Loading',
  pending: 'Awaiting approval',
  edited: 'edited',
  commentLabel: 'Write a comment',
  tooLong: 'Too long',
  repliesGroup: (n) => `Replies to ${n}`,
};

export const composerLabels: ComposerLabels = {
  bodyLabel: 'What is on your mind?',
  bodyPlaceholder: 'Say something',
  counter: (u, m) => `${u} of ${m}`,
  audienceLegend: 'Who can see this?',
  audienceHelp: 'Choose an audience',
  visibility: {
    public: { label: 'Public', description: 'Anyone can see it' },
    followers: { label: 'Followers', description: 'People who follow you' },
    friends: { label: 'Friends', description: 'Your friends' },
    circle: { label: 'A circle', description: 'One of your circles' },
    selected: { label: 'Selected people', description: 'Only people you pick' },
    private: { label: 'Only me', description: 'Just you' },
  },
  teenNotice: 'Your account is private by default',
  teenPublicBlocked: 'Not available for accounts under 18',
  circleLabel: 'Circle',
  circleNone: 'No circles yet',
  circleChoose: 'Choose a circle',
  selectedLabel: 'Add people by username',
  selectedHelp: 'Type a username',
  selectedAdd: 'Add',
  selectedNotFound: 'No such person',
  selectedRemove: (n) => `Remove ${n}`,
  selectedList: 'Chosen people',
  selectedEmpty: 'Nobody yet',
  topicsLegend: 'Topics',
  topicsHelp: (m) => `Up to ${m}`,
  pollToggle: 'Add a poll',
  pollQuestion: 'Question',
  pollOption: (n) => `Option ${n}`,
  pollAddOption: 'Add option',
  pollRemoveOption: (n) => `Remove option ${n}`,
  pollMultiple: 'Allow several answers',
  pollDuration: 'Poll length',
  pollDurations: [
    { hours: null, label: 'No end' },
    { hours: 24, label: '1 day' },
  ],
  linkLabel: 'Link',
  linkHelp: 'Share a web address',
  locationToggle: 'Add my approximate location',
  locationHelp: 'Used for the Local tab',
  locationTeenBlocked: 'Not available under 18',
  locationDenied: 'Location not shared',
  locationReady: 'Location added',
  submit: 'Post',
  submitting: 'Posting',
  optional: 'optional',
  errors: {
    empty: 'Write something or add a poll',
    pollQuestion: 'Ask a question',
    pollOptions: 'Add at least two options',
    circle: 'Choose a circle',
    audience: 'Add at least one person',
    link: 'Enter a valid link',
    tooLong: 'Too long',
    tooMuchMedia: 'Too many attachments',
  },
};

export const profileLabels: ProfileHeaderLabels = {
  privateAccount: 'Private account',
  joined: (d) => `Joined ${d}`,
  followers: (n) => `${n} followers`,
  following: (n) => `${n} following`,
  friends: (n) => `${n} friends`,
  modes: { creator: 'Creator', professional: 'Professional', business: 'Business' },
  stats: 'Statistics',
  links: 'Links',
  privateNotice: 'This account is private',
  coverAlt: 'Cover',
};

export const author = { id: 'u1', username: 'ada', displayName: 'Ada Lovelace', avatarUrl: null };
export const makePost = (over: Partial<PostData> = {}): PostData => ({
  id: 'p1',
  author,
  body: 'Hello world https://example.com/x',
  visibility: 'public',
  createdAt: new Date(Date.now() - 3 * 3600_000).toISOString(),
  editedAt: null,
  topics: ['Music'],
  counts: { likes: 3, comments: 2, shares: 0, saves: 0 },
  viewer: { reaction: null, saved: false, isAuthor: false },
  poll: null,
  link: null,
  media: [],
  ...over,
});
export const makeComment = (over: Partial<CommentData> = {}): CommentData => ({
  id: 'c1',
  postId: 'p1',
  parentId: null,
  body: 'Nice one',
  author: { id: 'u2', username: 'grace', displayName: 'Grace Hopper', avatarUrl: null },
  counts: { likes: 1, replies: 0 },
  viewer: { reaction: null, isAuthor: false },
  pendingApproval: false,
  editedAt: null,
  createdAt: new Date().toISOString(),
  ...over,
});
