/**
 * Four-letter English words for Word ladder: 2054 everyday words, plurals and past tenses, with rude
 * and very obscure ones left out. Bundled so the server and both apps check rungs the same way, offline.
 * Kept in lines of plain text to stay small; FOUR_LETTER_WORDS is the sorted list.
 */
const LINES = [
  'able ably aced aces ache achy acid acme acne acre acts adds aero afar aged ages agog aide aids ails aims airs airy ajar akin alas alba alee ales alit',
  'ally alms aloe also alto alum amen amid amok amps anew anon ante anti ants apes apex apps apse aqua arch arcs area arid arks arms army arts arty ashy',
  'asks atom aunt aura auto avid avow away awed awes awry axed axes axis axle ayes',
  'babe baby back bade bags baht bail bait bake bald bale balk ball balm band bane bang bank bans barb bard bare barf bark barn bars base bash bask bass',
  'bate bath bats bawl bays bead beak beam bean bear beat beau beck beds beef been beep beer bees beet begs bell belt bend bent best beta bets bevy bias',
  'bibs bide bids bier bike bile bilk bill bind bins bird bite bits blab blah bled blew blip blob bloc blog blot blow blue blur boar boas boat bobs bode',
  'body bogs boil bold bolt bomb bond bone bong bonk bony book boom boon boor boos boot bops bore born boss both bout bowl bows boxy boys bozo brag bran',
  'brat bray bred brew brie brig brim brow buck buds buff bugs bulb bulk bull bump bunk buns bunt buoy burg burl burn burp burr bury bush busk buss bust',
  'busy buys buzz byes byte',
  'cabs cads cafe cage cake calf call calm came camp cams cane cans cant cape caps card care carp cars cart case cash cask cast cats cave cede cell cent',
  'chai chap char chat chef chew chia chic chin chip chit chop chow chub chug chum cite city clad clam clan clap claw clay clef clew clip clod clog clop',
  'clot club clue coal coat coax cobs coda code cogs coif coil coin cola cold colt coma comb come cone conk cons cook cool coop coos coot cope cops copy',
  'cord core cork corm corn cost cosy cote cots coup cove cowl cows cozy crab crag cram craw crew crib crop crow crux cube cubs cues cuff cuke cull cult',
  'cups curb curd cure curl curs curt cusp cuss cute cuts cyan cyst czar',
  'dabs dads daft dais dale dame damp dams dang dank dare dark darn dart dash data date daub dawn days daze dead deaf deal dean dear debt deck deed deem',
  'deep deer deft defy deli dell demo dens dent deny desk dews dewy dial dibs dice died dies diet digs dill dime dims dine ding dins dips dire dirt disc',
  'dish disk diva dive dock dodo does doff dogs dole doll dolt dome done dong dons doom door dorm dose dote doth dots dour dove down doze dozy drab drag',
  'dram drat draw dray dreg drew drip drop drub drug drum dual dubs duck duct dude duds duel dues duet duff duke dull duly dumb dump dune dung dunk duos',
  'dupe dusk dust duty dyad dyed dyes dyne',
  'each earl earn ears ease east easy eats eave ebbs ebon echo eddy edge edgy edit eels eggs egos elks elms else emit emus ends envy epic eras ergo espy',
  'etch euro even ever eves evil ewer exam exes exit expo eyed eyes',
  'face fact fade fads faff fail fain fair fake fall fame fang fans fare farm fast fate faun faux fawn fays faze fear feat feed feel fees feet fell felt',
  'fend fens fern feta feud fibs fief fife figs file fill film find fine fink fins fire firm firs fish fist fits five fizz flab flag flak flan flap flat',
  'flaw flax flay flea fled flee flew flex flip flit floe flog flop flow flub flue flux foal foam foes fogs foil fold folk fond font food fool foot ford',
  'fore fork form fort foul four fowl foxy frat fray free fret frog from fuel full fume fumy fund funk furl furs fury fuse fuss fuzz',
  'gags gain gait gala gale gall game gamy gang gape gaps garb gars gash gasp gate gave gawk gaze gear geek geld gels gems gene gent germ gets ghee gibe',
  'gift gigs gild gill gilt girl girt gist give glad glee glen glib glob glow glue glum glut gnat gnaw gnus goad goal goat gods goer goes gold golf gone',
  'gong good goof goon gore gory gosh gout gown grab grad gram gray grew grey grid grim grin grip grit grog grow grub gulf gull gulp gums gunk guns guru',
  'gush gust guts guys gyms gyre gyro',
  'hack hags hail hair hale half hall halo halt hams hand hang haps hard hare hark harm harp hart hash hate hath hats haul have hawk haze hazy head heal',
  'heap hear heat heck heed heel heft heir held helm help hemp hems hens herb herd here hero hers hewn hick hide high hike hill hilt hind hint hips hire',
  'hiss hits hive hoax hobs hoed hogs hold hole holy home hone honk hood hoof hook hoop hoot hope hops horn hose host hour howl hows hubs hued hues huff',
  'huge hugs hula hulk hull hums hung hunk hunt hurl hurt hush husk huts hymn hype',
  'ibex ibis iced ices icky icon idea ides idle idly idol ills imam imps inch info inks inky inns into ions iota iris irks iron isle isms itch item',
  'jabs jack jade jail jamb jams jars jaws jays jazz jean jeep jeer jell jerk jest jets jibe jigs jilt jinn jinx jive jobs jock joey jogs join joke jolt',
  'josh jots jowl joys judo jugs juke jump junk jury just jute',
  'kale keel keen keep kegs kelp kepi kept keys khan kick kids kill kiln kilo kilt kind king kink kiss kite kits kiwi knee knew knit knob knot know kudu',
  'labs lace lack lacy lads lady laid lain lair lake lama lamb lame lamp land lane lank laps lard lark lash lass last late laud lava lave lawn laws lays',
  'laze lazy lead leaf leak lean leap leek leer left legs lend lens lent less lest lets levy lewd liar lice lick lids lied lien lies lieu life lift like',
  'lilt lily limb lime limn limo limp line link lint lion lips lira lisp list live load loaf loam loan lobe lobs loch loci lock loft logo logs loin loll',
  'lone long look loom loon loop loot lord lore lose loss lost lots loud lout love lows luck lull lump lung lure lurk lush lust lute luxe lynx lyre',
  'mace mack made magi maid mail maim main make male mall malt mama mane many maps mare mark marl mars mart mash mask mass mast mate math mats maul maze',
  'mazy mead meal mean meat meek meet mega meld melt memo mend menu meow mere mesa mesh mess mete mews mica mice midi miff mike mild mile milk mill mime',
  'mind mine mini mink mint minx mire miso miss mist mite mitt moan moat mobs mock mode mojo mold mole molt moms monk mono mood moon moor moos moot mope',
  'mops more morn moss most mote moth move mown mows much muck muds mugs mule mull mums murk muse mush musk muss must mute mutt myth',
  'nags naif nail name nape naps nave navy near neat neck need neem neon nerd nest nets news newt next nibs nice nick nigh nine nips nits node nods noir',
  'none nook noon nope nori norm nose nosh nosy note noun nuke null numb nuns nuts',
  'oaks oars oath oats obey obit oboe odds odes odor offs ogle ogre oils oily okay okra omen omit once ones only onto onus onyx ooze oozy opal open opts',
  'opus oral orbs orca ores ouch ours oust outs ouzo oval oven over owed owes owls owns oxen',
  'pace pack pact pads page paid pail pain pair pale pall palm pals pane pang pans pant papa paps para pare park part pass past path pats pave pawn paws',
  'pays peak peal pear peas peat peck pecs peed peek peel peep peer pegs pelt pend pens pent peon perk perm peso pest pets pews phew pick pics pied pier',
  'pies pigs pika pike pile pill pine ping pink pins pint pipe pips pita pith pits pity plan play plea pled plod plop plot plow ploy plug plum plus pods',
  'poem poet pogo poke poky pole poll polo pomp pond pong pony pool poor pope pops pore pork port pose posh post posy pots pour pout pram pray prep prey',
  'prim prod prom prop pros prow pubs puce puck puff pugs pull pulp puma pump punk puns punt puny pups pure purr push puts putt',
  'quay quid quip quit quiz',
  'race rack racy raft rage rags raid rail rain rake ramp rams rang rank rant raps rapt rare rash rasp rate rats rave rays raze razz read real ream reap',
  'rear redo reds reed reef reek reel refs rein rely rend rent repo reps rest ribs rice rich ride rids rife riff rift rigs rile rims rind ring rink riot',
  'ripe rips rise risk rite road roam roar robe robs rock rode rods roes role roll romp rood roof rook room root rope ropy rose rosy rote rots rout roux',
  'rove rows rubs ruby rude rued rues ruff rugs ruin rule rums rune rung runs runt ruse rush rust ruts ryes',
  'sack sacs safe saga sage said sail sake sale salt same sand sane sang sank saps sari sash sass sate save sawn saws says scab scam scan scar scat scry',
  'scum seal seam sear seas seat sect seed seek seem seen seep sees self sell semi send sent sets sewn sews sham shed shin ship shoe shoo shop shot show',
  'shun shut sick side sift sigh sign silk sill silo silt sing sink sins sips sire site sits size skew skid skim skin skip skis skua slab slag slam slap',
  'slat slaw slay sled slew slid slim slip slit slob slog slop slot slow slug slum slur smog smug snag snap snip snit snob snot snow snub snug soak soap',
  'soar sobs sock soda sofa soft soil sold sole solo some song sons soon soot sore sort soul soup sour sown sows soya spam span spar spat spec sped spew',
  'spin spit spot spry spud spun spur stab stag star stay stem step stew stir stop stow stub stud stun subs such suds sued sues suet suit sulk sumo sump',
  'sums sung sunk suns sure surf swab swag swam swan swap swat sway swig swim swot swum',
  'tabs tack taco tact tags tail take talc tale talk tall tame tang tank tans tape taps tarn taro tarp tars tart task taut taxi teak teal team tear teas',
  'tech teem teen tees teff tell temp tend tens tent term tern test text than that thaw thee them then they thin this thud thug thus tick tide tidy tied',
  'tier ties tile till tilt time ting tins tint tiny tips tire toad toed toes tofu toga togs toil told tole toll tomb tome tone tong tons took tool toot',
  'tope tops tore torn toss tour tout town tows toys tram trap tray tree trek trig trim trio trip trod trot true tsar tuba tube tubs tuck tuft tugs tuna',
  'tune turf turn tusk tutu twee twig twin twos type typo',
  'ugly ulna undo unit unto updo upon urge used user uses',
  'vain vamp vane vans vary vase vast vats veal veep veer veil vein vend vent verb very vest veto vets vial vibe vice vied view vile vine vino visa vise',
  'viva void vole volt vote vows',
  'wack wade wads waft wage wags waif wail wait wake walk wall wand wane want ward warm warn warp wars wart wary wash wasp watt wave wavy waxy ways weak',
  'wean wear webs weds weed week weep weft weld well went wept were west what whee when whet whew whey whim whip whiz whoa whom wick wide wife wigs wiki',
  'wild will wilt wily wimp wind wine wing wink wins wipe wire wiry wise wish wisp with wits woes woke woks wolf womb wonk wood woof wool woos word wore',
  'work worm worn wort wove wows wrap wren writ',
  'yaks yams yank yaps yard yarn yawn yaws yeah year yell yelp yens yeti yews yips yoga yoke yolk yore your yuck yurt',
  'zany zaps zeal zero zest zinc zing zips zone zoom zoos',
];

export const FOUR_LETTER_WORDS: readonly string[] = LINES.join(' ').split(' ');
