/**
 * Throwaway-inbox providers. A sign-up from one of these adds a risk signal; it
 * never blocks the sign-up on its own. Subdomains match too (x.mailinator.com).
 * Deliberately limited to services that exist to hand out disposable addresses;
 * privacy forwarding services (which people use for real accounts) are not here.
 */
export const DISPOSABLE_DOMAINS = new Set([
  '10minemail.com',
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.co.uk',
  '1secmail.com',
  '1secmail.net',
  '1secmail.org',
  '20minutemail.com',
  '33mail.com',
  'armyspy.com',
  'bccto.me',
  'burnermail.io',
  'byom.de',
  'chacuo.net',
  'cool.fr.nf',
  'courriel.fr.nf',
  'cuvox.de',
  'dayrep.com',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'dispostable.com',
  'dropmail.me',
  'einrot.com',
  'emailfake.com',
  'emailondeck.com',
  'emltmp.com',
  'esiix.com',
  'fakeinbox.com',
  'fakemail.net',
  'fakemailgenerator.com',
  'fleckens.hu',
  'getairmail.com',
  'getnada.com',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'harakirimail.com',
  'inboxkitten.com',
  'incognitomail.org',
  'jetable.fr.nf',
  'jetable.org',
  'jourrapide.com',
  'linshiyouxiang.net',
  'mailcatch.com',
  'maildrop.cc',
  'mailexpire.com',
  'mailforspam.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator2.com',
  'mailnesia.com',
  'mailpoof.com',
  'mailsac.com',
  'mega.zik.dj',
  'mintemail.com',
  'mohmal.com',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'mvrht.com',
  'mytemp.email',
  'nada.email',
  'nomail.xl.cx',
  'nospam.ze.tc',
  'owlymail.com',
  'pokemail.net',
  'rhyta.com',
  'sharklasers.com',
  'spam4.me',
  'spambox.us',
  'spamdecoy.net',
  'spamgourmet.com',
  'speed.1s.fr',
  'superrito.com',
  'teleworm.us',
  'tempail.com',
  'tempemail.net',
  'tempinbox.com',
  'tempmail.com',
  'tempmail.net',
  'tempmail.plus',
  'tempmailo.com',
  'temp-mail.io',
  'temp-mail.org',
  'tempr.email',
  'throwam.com',
  'throwawaymail.com',
  'tmpmail.net',
  'tmpmail.org',
  'trashmail.com',
  'trashmail.de',
  'trashmail.io',
  'trashmail.net',
  'vomoto.com',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wwjmp.com',
  'xojxe.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'zetmail.com',
]);

/** True when the address's domain, or a parent of it, is a throwaway-inbox provider. */
export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@').pop()?.trim().toLowerCase() ?? '';
  const parts = domain.split('.');
  for (let i = 0; i < parts.length - 1; i++) if (DISPOSABLE_DOMAINS.has(parts.slice(i).join('.'))) return true;
  return false;
}
