// Writes lib/region-names.ts: every country's name in each of the app's languages, from Node's
// full Unicode data. The phone's JavaScript engine has no Intl.DisplayNames, so it reads these.
// Run again after adding a language: node scripts/region-names.mjs
import { writeFileSync } from 'node:fs';

const LANGS = ['en', 'fr', 'ar', 'es', 'pt', 'sw', 'yo', 'ha'];
const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const en = new Intl.DisplayNames(['en'], { type: 'region', fallback: 'none' });
const codes = [];
for (const a of letters)
  for (const b of letters) {
    const c = a + b;
    // Real countries only: a name exists, and it isn't a reserved or grouping code.
    if (en.of(c) && !['EU', 'EZ', 'UN', 'QO', 'XA', 'XB', 'ZZ'].includes(c)) codes.push(c);
  }
const table = {};
for (const l of LANGS) {
  const dn = new Intl.DisplayNames([l], { type: 'region', fallback: 'none' });
  table[l] = Object.fromEntries(codes.map((c) => [c, dn.of(c) ?? en.of(c)]));
}
const out = `// Generated by scripts/region-names.mjs from Node's Unicode data. Don't edit by hand.
/* eslint-disable */
export const REGION_NAMES: Record<string, Record<string, string>> = ${JSON.stringify(table)};
`;
writeFileSync(new URL('../lib/region-names.ts', import.meta.url), out);
console.log(codes.length, 'countries');
