/**
 * Generates src/theme/tokens.generated.ts from packages/design-system/src/tokens.css (the single source of truth for
 * YAPILAPI's brand tokens). React Native has no CSS variables, so we compile them to plain numbers/strings.
 *   npm run tokens          rewrite the generated file
 *   npm run tokens -- --check   exit 1 when the file is stale (also enforced by test/tokens.test.ts)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
export const CSS_PATH = path.resolve(here, '../../../packages/design-system/src/tokens.css');
export const OUT_PATH = path.resolve(here, '../src/theme/tokens.generated.ts');

const camel = (s: string) => s.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function block(css: string, selector: string): Record<string, string> {
  const start = css.indexOf(`${selector} {`);
  if (start < 0) throw new Error(`selector not found: ${selector}`);
  const end = css.indexOf('\n}', start);
  const body = css.slice(start, end);
  const out: Record<string, string> = {};
  for (const m of body.matchAll(/--yl-([a-z0-9-]+):\s*([^;]+);/g))
    out[m[1]!] = m[2]!.replace(/\/\*.*?\*\//g, '').trim();
  return out;
}

function px(v: string): number {
  const clamp = /^clamp\(\s*([^,]+),/.exec(v);
  const s = clamp ? clamp[1]!.trim() : v;
  if (s.endsWith('rem')) return Math.round(parseFloat(s) * 16 * 100) / 100;
  if (s.endsWith('px')) return parseFloat(s);
  if (s === '0') return 0;
  throw new Error(`cannot convert ${v} to px`);
}

function color(v: string): string {
  const m = /^rgb\(\s*(\d+)\s+(\d+)\s+(\d+)\s*\/\s*([\d.]+)\s*\)$/.exec(v);
  return m ? `rgba(${m[1]}, ${m[2]}, ${m[3]}, ${m[4]})` : v;
}

export function generate(css: string): string {
  const light = block(css, ':root');
  const dark = block(css, ":root[data-theme='dark']");
  const roles = (b: Record<string, string>) =>
    Object.fromEntries(
      Object.entries(b)
        .filter(([k]) => k.startsWith('color-'))
        .map(([k, v]) => [camel(k.slice(6)), color(v)]),
    );
  const lightColors = roles(light);
  const darkColors = { ...lightColors, ...roles(dark) };
  const pick = (prefix: string, conv: (v: string) => number | string) =>
    Object.fromEntries(
      Object.entries(light)
        .filter(([k]) => k.startsWith(prefix))
        .map(([k, v]) => [camel(k.slice(prefix.length)), conv(v)]),
    );
  const ms = (v: string) => parseFloat(v);
  const tokens = {
    colors: { light: lightColors, dark: darkColors },
    space: pick('space-', px),
    radius: Object.fromEntries(
      Object.entries(pick('radius-', (v) => (v.endsWith('%') ? v : px(v)))).filter(
        ([k]) => k !== 'pebble',
      ),
    ),
    pebble: light['radius-pebble'],
    fontSize: pick('text-', px),
    weight: pick('weight-', (v) => String(Math.round(parseFloat(v)))),
    leading: pick('leading-', (v) => parseFloat(v)),
    durationMs: pick('dur-', ms),
    targetMin: px(light['target-min']!),
    brand: {
      ember: light['ember-500'],
      lagoon: light['lagoon-500'],
      saffron: light['saffron-500'],
    },
  };
  return `/* GENERATED by scripts/sync-tokens.mts from packages/design-system/src/tokens.css. Do not edit by hand. */\nexport const tokens = ${JSON.stringify(tokens, null, 2)} as const;\n`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const next = generate(readFileSync(CSS_PATH, 'utf8'));
  if (process.argv.includes('--check')) {
    let cur = '';
    try {
      cur = readFileSync(OUT_PATH, 'utf8');
    } catch {
      /* missing */
    }
    if (cur !== next) {
      console.error('tokens.generated.ts is stale: run `npm run tokens` in apps/mobile');
      process.exit(1);
    }
  } else {
    writeFileSync(OUT_PATH, next);
    console.log(`wrote ${path.relative(process.cwd(), OUT_PATH)}`);
  }
}
