/**
 * Generates docs/api/routes.md from the live route table so the endpoint list
 * can't drift from the code. Run: pnpm --filter @yapilapi/api docs:routes
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildApp } from '../src/app.ts';
import { loadConfig } from '../src/config.ts';
import { requireAuth } from '../src/plugins/auth.ts';

interface Row {
  method: string;
  url: string;
  access: string;
  limit: string;
}
const rows: Row[] = [];

const config = loadConfig({ ...process.env, REDIS_URL: '', DATABASE_URL: process.env.DATABASE_URL ?? 'postgres://postgres:postgres@localhost:5432/yapilapi' });
const { close } = await buildApp(config, {
  logger: false,
  onRoute: (r) => {
    if (r.method === 'HEAD' || (Array.isArray(r.method) && r.method.includes('HEAD'))) return;
    const pre = ([] as unknown[]).concat(r.preHandler ?? []);
    const role = pre.find((h): h is { roles: string[] } => typeof h === 'function' && 'roles' in h);
    const access = pre.includes(requireAuth) ? 'user' : role ? role.roles.join(' or ') : r.url.startsWith('/v1/realtime') ? 'user (socket)' : 'public';
    const cfg = (r.config ?? {}) as { rateLimit?: false | { max: number; timeWindow: string } };
    const limit = cfg.rateLimit === false ? 'none' : cfg.rateLimit ? `${cfg.rateLimit.max} / ${cfg.rateLimit.timeWindow}` : 'default';
    rows.push({ method: String(r.method), url: r.url, access, limit });
  },
});
await close();

rows.sort((a, b) => a.url.localeCompare(b.url) || a.method.localeCompare(b.method));
const md = [
  '# API routes',
  '',
  'Generated by `apps/api/scripts/gen-routes.ts` from the running route table. Do not edit by hand.',
  '',
  `${rows.length} routes. Access: **public** (session optional; results still filtered by visibility), **user** (valid session required), **moderator / admin** (platform role, enforced on the server). Default rate limit: ${config.RATE_LIMIT_MAX} requests per minute per user or IP.`,
  '',
  '| Method | Path | Access | Rate limit |',
  '| --- | --- | --- | --- |',
  ...rows.map((r) => `| ${r.method} | \`${r.url}\` | ${r.access} | ${r.limit} |`),
  '',
].join('\n');
const out = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../docs/api/routes.md');
await writeFile(out, md);
console.log(`wrote ${rows.length} routes to ${out}`);
